export const pageRoutes = {
  home: '/',
  login: '/login',
  register: 'register',
  createAccessKey: '/access-key/create',
  listAccessKeys: '/access-key/list',
  createCollection: '/collection/create',
  updateCollection: '/collection/update',
  listCollections: '/collection/list',
  collectionDetail: '/collection/detail',
  updateObject: '/object/update',
  createSchema: '/schema/create',
  listSchemas: '/schema/list',
  updateSchema: '/schema/update',
  schemaDetail: '/schema/detail',
  createUser: '/user/create',
  listUsers: '/user/list',
  updateUser: '/user/update',
  collectionDoc: '/docs/collection',
  schemaDoc: '/docs/schema',
  userDoc: '/docs/user',
  accessKeyDoc: '/docs/access-key',
  apiRefDoc: '/docs/api'
}
