export const env = {
  DB_NAME: process.env.DB_NAME,
  DB_SCHEMA: process.env.DB_SCHEMA,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_HOST: process.env.DB_HOST,

  GOOGLE_STORAGE_BUCKET_NAME: process.env.GOOGLE_STORAGE_BUCKET_NAME,
  GOOGLE_STORAGE_PREFIX: process.env.GOOGLE_STORAGE_PREFIX,
  GOOGLE_STORAGE_TRASH_FOLDER: process.env.GOOGLE_STORAGE_TRASH_FOLDER,

  NODE_ENV: process.env.NODE_ENV
}
