export const env = {
  MF_SCHEMA_ACCOUNT_DB_KEY: process.env.MF_SCHEMA_ACCOUNT_DB_KEY,
  JWT_SECRET: process.env.JWT_SECRET,
  USER_JWT_SECRET: process.env.USER_JWT_SECRET,
  GOOGLE_STORAGE_BUCKET_NAME: process.env.GOOGLE_STORAGE_BUCKET_NAME,
  RECOVER_EMAIL_SENDER: process.env.RECOVER_EMAIL_SENDER_ADDRESS,
  RECOVER_EMAIL_SENDER_PASSWORD: process.env.RECOVER_EMAIL_SENDER_PASSWORD,
  GCP_STORAGE_CLIENT_EMAIL: process.env.GCP_STORAGE_CLIENT_EMAIL,
  GCP_STORAGE_PRIVATE_KEY: process.env.GCP_STORAGE_PRIVATE_KEY,

  NODE_ENV: process.env.NODE_ENV
}
